### Get All Auctions
GET {{host}}/api/auctions
Accept: application/json

### Get Auction by ID
GET {{host}}/api/auctions/1
Accept: application/json

### Create Auction
POST {{host}}/api/auctions
Content-Type: application/json
Accept: application/json

{
  "title": "New Auction Title",
  "description": "New auction description",
  "startPrice": 500,
  "startTime": "2023-10-01T10:00:00",
  "endTime": "2023-10-10T10:00:00",
  "sellerId": 1
}

### Update Auction
PUT {{host}}/api/auctions/2
Content-Type: application/json
Accept: application/json

{
  "title": "Updated Auction Title",
  "description": "Updated auction description",
  "startPrice": 350000,
  "startTime": "2023-10-02T10:00:00",
  "endTime": "2023-10-11T10:00:00"
}

### Delete Auction
DELETE {{host}}/api/auctions/1
Accept: application/json



